### ISSUE TITLE
Two words surnames do not work well with TPLP format

### ISSUE THREAD

**Issue by jorgefandinno** [krr-up/bibliography#184]
Currently there are three different ways in which surnames with more than one word are written in the ```kr.bib``` file. See ```Luis Fariñas del cerro in the following entries: 
https://github.com/krr-up/bibliography/blob/c9ff60e1a1786fb63c647a0fc2ea9449e58b4301/krr.bib#L3446
https://github.com/krr-up/bibliography/blob/c9ff60e1a1786fb63c647a0fc2ea9449e58b4301/krr.bib#L2633
https://github.com/krr-up/bibliography/blob/c9ff60e1a1786fb63c647a0fc2ea9449e58b4301/krr.bib#L9736

With the TPLP format, the first produces ``(...  del Cerro ...)`` instead of ``(... Fariñas del Cerro ...)``. This is not a problem with format that use numbers instead of names.

I did not try the third option, but it should work as well.

Now that we have an automatic tool to format names, we could add the functionality to correctly format surnames with more than one word. The options I am aware of are ``L. {Fari{\~{n}}as del Cerro}`` or ``Fari{\~{n}as del Cerro, L.``

Comments?

**Comment by tortinator** [comment]
Thanks @jorgefandinno ! Let's try to discuss while being at Corunna. Gracias!

**Comment by rkaminsk** [comment]
In our current style, it would have to be `L. {Fari{\~{n}}as del Cerro}` and not `Fari{\~{n}as del Cerro, L.` I would not mind the latter as it involves less squiggles. If we chose the latter, we should probably rewrite all entries.

With our current scripts, it should not be difficult to implement either of the two options. Since it's Torstens style, maybe he should flip the coin. :wink: The generated bibliography will look the same anyway.

**Comment by tortinator** [comment]
Hi, I'd actually prefer putting the full last name into `{...}`, which amounts to  `L. {Fari{\~{n}}as del Cerro}`

In general I'd happy to overcome all features/issues, which are due to a historic evolution of the entries ...

**Comment by jorgefandinno** [comment]
Ok, I think it should be relatively easy to add this to the [authfmt.py](https://github.com/krr-up/bibliography/blob/master/authfmt.py) script.

Would that make sense?
